const books = [
  {
    book_id: 1,
    title: "Lost in Math",
    image_url: "https://otimages.com/Bookcover/4257/9780465094257.jpg",
    writer: "Sabine Hossenfelder",
    location: "Room A",
    description: "A contrarian argues that modern physicists' obsession with beauty has given us wonderful math but bad science Whether pondering black holes or predicting discoveries at CERN, physicists believe the best theories are beautiful, natural, and elegant, and this standard separates popular theories from disposable ones. This is why, Sabine Hossenfelder argues, we have not seen a major breakthrough in the foundations of physics for more than four decades. The belief in beauty has become so dogmatic that it now conflicts with scientific objectivity: observation has been unable to confirm mindboggling theories, like supersymmetry or grand unification, invented by physicists based on aesthetic criteria. Worse, these too good to not be true theories are actually untestable and they have left the field in a cul-de-sac. To escape, physicists must rethink their methods. Only by embracing reality as it is can science discover the truth.",
    created_at: "12 Juni 2018",
    updated_at: "5 July 2019",
  },
  {
    book_id: 2,
    title: "Mapping the Heavens",
    image_url: "https://otimages.com/Bookcover/7031/9780300227031.jpg",
    writer: "Priyamvada Natarajan",
    location: "Room A",
    description: "For all curious readers, a lively introduction to radical ideas and discoveries that are transforming our knowledge of the universe This book provides a tour of the greatest hits of cosmological discoveries--the ideas that reshaped our universe over the past century. The cosmos, once understood as a stagnant place, filled with the ordinary, is now a universe that is expanding at an accelerating pace, propelled by dark energy and structured by dark matter. Priyamvada Natarajan, our guide to these ideas, is someone at the forefront of the research--an astrophysicist who literally creates maps of invisible matter in the universe. She not only explains for a wide audience the science behind these essential ideas but also provides an understanding of how radical scientific theories gain acceptance. The formation and growth of black holes, dark matter halos, the accelerating expansion of the universe, the echo of the big bang, the discovery of exoplanets, and the possibility of other universes--these are some of the puzzling cosmological topics of the early twenty-first century. Natarajan discusses why the acceptance of new ideas about the universe and our place in it has never been linear and always contested even within the scientific community. And she affirms that, shifting and incomplete as science always must be, it offers the best path we have toward making sense of our wondrous, mysterious universe.",
    created_at: "23 May 2017",
    updated_at: "5 July 2019",
  },
  {
    book_id: 3,
    title: "Homo Deus",
    image_url: "https://otimages.com/Bookcover/4316/9780062464316.jpg",
    writer: "Yuval Noah Harari",
    location: "Room B",
    description: "Yuval Noah Harari, author of the critically-acclaimed New York Times bestseller and international phenomenon Sapiens, returns with an equally original, compelling, and provocative book, turning his focus toward humanity's future, and our quest to upgrade humans into gods.Over the past century humankind has managed to do the impossible and rein in famine, plague, and war. This may seem hard to accept, but, as Harari explains in his trademark style--thorough, yet riveting--famine, plague and war have been transformed from incomprehensible and uncontrollable forces of nature into manageable challenges. For the first time ever, more people die from eating too much than from eating too little; more people die from old age than from infectious diseases; and more people commit suicide than are killed by soldiers, terrorists and criminals put together. The average American is a thousand times more likely to die from binging at McDonalds than from being blown up by Al Qaeda. What then will replace famine, plague, and war at the top of the human agenda? As the self-made gods of planet earth, what destinies will we set ourselves, and which quests will we undertake? Homo Deus explores the projects, dreams and nightmares that will shape the twenty-first century--from overcoming death to creating artificial life. It asks the fundamental questions: Where do we go from here? And how will we protect this fragile world from our own destructive powers? This is the next stage of evolution. This is Homo Deus. With the same insight and clarity that made Sapiens an international hit and a New York Times bestseller, Harari maps out our future.",
    created_at: "5 July 2019",
    updated_at: "5 July 2019",
  },
  {
    book_id: 4,
    title: "The Search for What Lies Beyond the Quantum",
    image_url: "https://otimages.com/Bookcover/6191/9781594206191.jpg",
    writer: "Lee Smolin",
    location: "Room B",
    description: "A daring new vision of quantum theory from one of the leading minds of contemporary physics Quantum physics is the golden child of modern science. It is the basis of our understanding of atoms, radiation, and so much else, from elementary particles and basic forces to the behavior of materials. But for a century it has also been the problem child of science: it has been plagued by intense disagreements between its inventors, strange paradoxes, and implications that seem like the stuff of fantasy. Whether it's Schr dinger's cat--a creature that is simultaneously dead and alive--or a belief that the world does not exist independently of our observations of it, quantum theory challenges our fundamental assumptions about reality.In Einstein's Unfinished Revolution, theoretical physicist Lee Smolin provocatively argues that the problems which have bedeviled quantum physics since its inception are unsolved and unsolvable, for the simple reason that the theory is incomplete. There is more to quantum physics, waiting to be discovered. Our task--if we are to have simple answers to our simple questions about the universe we live in--must be to go beyond quantum mechanics to a description of the world on an atomic scale that makes sense.In this vibrant and accessible book, Smolin takes us on a journey through the basics of quantum physics, introducing the stories of the experiments and figures that have transformed our understanding of the universe, before wrestling with the puzzles and conundrums that the quantum world presents. Along the way, he illuminates the existing theories that might solve these problems, guiding us towards a vision of the quantum that embraces common sense realism. If we are to have any hope of completing the revolution that Einstein began nearly a century ago, we must go beyond quantum mechanics to find a theory that will give us a complete description of nature. In Einstein's Unfinished Revolution, Lee Smolin brings us a step closer to resolving one of the greatest scientific controversies of our age.",
    created_at: "9 April 2019",
    updated_at: "5 July 2019",
  },
  {
    book_id: 5,
    title: "Astrophysic for People in a Hurry",
    image_url: "https://otimages.com/Bookcover/9394/9780393609394.jpg",
    writer: "Neil deGrasse Tyson",
    location: "Room B",
    description: "What is the nature of space and time? How do we fit within the universe? How does the universe fit within us? There's no better guide through these mind-expanding questions than acclaimed astrophysicist and best-selling author Neil deGrasse Tyson. But today, few of us have time to contemplate the cosmos. So Tyson brings the universe down to Earth succinctly and clearly, with sparkling wit, in tasty chapters consumable anytime and anywhere in your busy day. While you wait for your morning coffee to brew, for the bus, the train, or a plane to arrive, Astrophysics for People in a Hurry will reveal just what you need to be fluent and ready for the next cosmic headlines: from the Big Bang to black holes, from quarks to quantum mechanics, and from the search for planets to the search for life in the universe.",
    created_at: "02 May 2017",
    updated_at: "5 July 2019",
  },
  {
    book_id: 6,
    title: "Death by Black Hole",
    image_url: "https://otimages.com/Bookcover/2243/9780393062243.jpg",
    writer: "Neil deGrasse Tyson",
    location: "Room B",
    description: "A vibrant collection of essays on the cosmos is delivered by the nation's best-known astrophysicist, who is popular for his monthly Universe essays in Natural History magazine. ...Known for his ability to blend content, accessibility, and humor, Tyson is a natural teacher who simplifies some of the most complex concepts in astrophysics while simultaneously sharing his infectious excitement about our universe.",
    created_at: "01 November 2006",
    updated_at: "5 July 2019",
  }
]

export default books;
